
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart (FILE *input_file ,yyscan_t yyscanner );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void yy_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yy_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void yypop_buffer_state (yyscan_t yyscanner );

static void yyensure_buffer_stack (yyscan_t yyscanner );
static void yy_load_buffer_state (yyscan_t yyscanner );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void *yyalloc (yy_size_t ,yyscan_t yyscanner );
void *yyrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void yyfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 120
#define YY_END_OF_BUFFER 121
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[275] =
    {   0,
        0,    0,    0,    0,    0,    0,   92,   92,   94,   94,
       97,   97,  100,  100,   92,   92,   94,   94,   97,   97,
      100,  100,  121,    1,  120,    2,  120,   90,    6,    5,
       90,   20,    7,   44,   53,   19,   15,   18,   40,   38,
       32,   39,   31,   42,   10,   10,   11,   34,   33,   45,
       35,   46,   36,   89,   89,   89,   13,   90,   16,   52,
       37,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   14,   55,   17,
       54,    4,    3,   92,  101,   91,  120,   94,   93,   97,
      102,   96,  100,   99,  120,    1,    0,    2,    0,    0,

        6,   49,    0,    7,    0,   41,   43,    0,   10,    0,
        0,    0,   10,   11,    5,   56,   50,   47,   48,   51,
       57,   89,   24,   23,   89,   28,   27,   89,    8,   89,
       85,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   63,   89,   61,   62,   89,   89,   60,   89,   89,
       89,   89,   89,   89,   89,   89,   92,  117,  106,  109,
      108,  105,  107,  110,  111,  112,  113,  114,  115,  116,
      117,  104,   94,   97,   96,  100,   99,  119,  118,   22,
       21,    9,    0,    9,   12,    0,    0,    0,    0,   58,
       89,   89,   89,   89,   80,   87,   89,   89,   89,   89,

       89,   70,   89,   89,   89,   89,   59,   89,   89,   89,
       89,   74,   89,   89,   89,  105,    0,   95,   98,    0,
       26,   25,   30,   29,   89,   89,   89,   89,   64,   65,
       89,   88,   89,   82,   89,   89,   89,   66,   89,   89,
       89,   89,   86,   89,  105,  103,    0,    9,   89,   72,
       79,   89,   89,   89,   89,   89,   89,   69,   76,   89,
       71,   68,   75,   89,   77,   89,   83,   84,   81,   67,
       89,   78,   73,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,    1,   26,   27,   27,   27,   27,   28,   27,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   30,   29,   29,   31,   29,   29,   29,   29,   29,
       32,   33,   34,   35,   29,   36,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   29,   46,   47,   48,   49,
       50,   51,   29,   52,   53,   54,   55,   56,   57,   58,
       59,   29,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   64,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[65] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        1,    1,    1,    1,    1,    1,    5,    5,    6,    6,
        6,    1,    7,    1,    1,    1,    5,    5,    5,    5,
        5,    5,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    1,
        1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[294] =
    {   0,
        0,    2,    8,    0,  463,  462,   70,   71,   72,   73,
       78,   79,   80,   81,   86,   87,   88,   89,   98,   99,
       94,   95,  464,  467,  123,  467,  460,  467,  460,  467,
      437,  455,    0,  467,  467,  450,  467,  467,  446,  467,
      467,  467,  467,  440,  117,  122,  128,  467,  453,   92,
      431,   85,  467,    0,  134,  125,  467,  451,  467,  467,
      467,  100,  401,  104,  411,  110,  114,  404,  125,  413,
      399,  396,  124,  174,  395,   79,  401,  467,  467,  467,
      467,  467,  467,    0,  467,  467,  227,    0,  467,    0,
      467,  436,    0,  439,  440,  467,  178,  467,  439,  438,

      438,  467,  434,    0,  429,  467,  467,  152,  172,  178,
      189,    0,  198,  215,  467,  467,  467,  467,  467,  467,
      467,    0,  432,  427,  190,  430,  425,  177,  467,  393,
      379,  390,  393,  380,  180,  107,  146,  379,  375,  376,
      375,    0,  373,    0,    0,  375,  368,    0,  368,  375,
      374,  364,  358,  371,  361,  373,    0,  467,  467,  467,
      467,  205,  467,  467,  467,  467,  467,  467,  467,  467,
        0,  467,    0,    0,  404,    0,  407,  467,  467,  467,
      467,  229,  232,  235,    0,  406,  401,  404,  399,    0,
      366,  369,  352,  350,    0,    0,  361,  361,  360,  361,

      362,    0,  350,  359,  346,  357,    0,  331,  334,  326,
      322,    0,  325,  327,  313,  219,    0,  467,  467,  248,
      467,  467,  467,  467,  306,  303,  237,  244,    0,    0,
      233,    0,  235,    0,  243,  226,  237,    0,  221,  233,
      210,  218,    0,  218,  467,  467,  253,  268,  190,    0,
        0,  192,  186,  181,  178,  167,  175,    0,    0,  161,
        0,    0,    0,  148,    0,  142,    0,    0,    0,    0,
      152,    0,    0,  467,  291,  298,  305,  312,  319,  326,
      333,  340,  347,  350,  356,  362,  369,  375,  381,  387,
      157,  113,    2

    } ;

static yyconst flex_int16_t yy_def[294] =
    {   0,
      275,  275,  274,    3,  276,  276,  277,  277,  278,  278,
      279,  279,  280,  280,  277,  277,  278,  278,  279,  279,
      280,  280,  274,  274,  281,  274,  282,  274,  274,  274,
      274,  274,  283,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  284,  284,  284,  274,  274,  274,  274,
      274,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  274,  274,  274,
      274,  274,  274,  285,  274,  274,  286,  287,  274,  288,
      274,  274,  289,  274,  290,  274,  281,  274,  282,  282,

      274,  274,  274,  283,  274,  274,  274,  274,  274,  274,
      274,  291,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  284,  274,  274,  284,  274,  274,  284,  274,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  285,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      292,  274,  287,  288,  274,  289,  274,  274,  274,  274,
      274,  274,  274,  274,  291,  274,  274,  274,  274,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  274,  293,  274,  274,  274,
      274,  274,  274,  274,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  274,  274,  274,  274,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,    0,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274

    } ;

static yyconst flex_int16_t yy_nxt[532] =
    {   0,
      274,   25,   26,   25,   26,   27,  246,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,   53,   54,   54,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
       68,   54,   69,   54,   70,   54,   71,   72,   73,   74,
       54,   75,   56,   54,   76,   54,   77,   78,   79,   80,
       81,   28,   85,   85,   85,   85,   89,   89,   86,   86,
       91,   91,   91,   91,   94,   94,   92,   92,   85,   85,
       85,   85,   89,   89,   86,   86,   91,   91,   94,   94,

       91,   91,   87,   87,   87,   87,   92,   92,  120,  121,
       87,   87,   87,   87,  116,  117,  118,  217,   95,   95,
       95,   95,  154,  155,   97,   98,   95,   95,   99,  126,
       95,   95,  108,  127,  109,  109,  110,  108,  123,  113,
      113,  114,  124,  108,  111,  114,  114,  114,  130,  111,
      133,  197,  131,  134,  128,  111,  136,  111,  138,  198,
      149,  185,  111,  139,  125,  140,  142,  137,  111,  182,
      182,  182,  143,  144,  112,  150,  128,  145,  123,   97,
       98,  126,  124,   99,  199,  127,  200,  108,  125,  109,
      109,  110,  273,  108,  126,  110,  110,  110,  127,  111,

      272,  183,  271,  183,  125,  111,  184,  184,  184,  270,
      151,  269,  111,  108,  152,  113,  113,  114,  111,  128,
      268,  195,  216,  216,  267,  111,  196,  266,  125,  159,
      108,  160,  114,  114,  114,  161,  245,  245,  111,  265,
      264,  128,  111,  263,  162,  162,  182,  182,  182,  184,
      184,  184,  184,  184,  184,  111,  220,  262,  261,  163,
      247,  260,  247,  164,  165,  248,  248,  248,  166,  220,
      248,  248,  248,  259,  258,  167,  257,  256,  168,  255,
      169,  254,  170,  253,  171,  248,  248,  248,  252,  251,
      172,   24,   24,   24,   24,   24,   24,   24,   82,   82,

       82,   82,   82,   82,   82,   84,   84,   84,   84,   84,
       84,   84,   88,   88,   88,   88,   88,   88,   88,   90,
       90,   90,   90,   90,   90,   90,   93,   93,   93,   93,
       93,   93,   93,   96,   96,   96,   96,   96,   96,   96,
      100,  100,  100,  100,  100,  100,  100,  104,  250,  104,
      104,  104,  104,  104,  122,  122,  157,  249,  157,  244,
      157,  157,  158,  158,  158,  158,  158,  158,  158,  173,
      243,  242,  173,  173,  173,  174,  241,  174,  240,  174,
      174,  176,  239,  238,  176,  176,  176,  178,  178,  178,
      178,  178,  178,  178,  237,  236,  235,  234,  233,  232,

      231,  230,  229,  228,  227,  226,  225,  224,  223,  222,
      221,  219,  218,  215,  214,  213,  212,  211,  210,  209,
      208,  207,  206,  205,  204,  203,  202,  201,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  181,  180,  101,
       98,   98,  179,  177,  175,  156,  153,  148,  147,  146,
      141,  135,  132,  129,  119,  115,  107,  106,  105,  103,
      102,  101,   98,  274,   83,   83,   23,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,

      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274
    } ;

static yyconst flex_int16_t yy_chk[532] =
    {   0,
        0,    1,    1,    2,    2,    1,  293,    2,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    7,    8,    9,   10,    9,   10,    7,    8,
       11,   12,   13,   14,   13,   14,   11,   12,   15,   16,
       17,   18,   17,   18,   15,   16,   21,   22,   21,   22,

       19,   20,    7,    8,    9,   10,   19,   20,   52,   52,
       11,   12,   13,   14,   50,   50,   50,  292,   15,   16,
       17,   18,   76,   76,   25,   25,   21,   22,   25,   56,
       19,   20,   45,   56,   45,   45,   45,   46,   55,   46,
       46,   46,   55,   47,   45,   47,   47,   47,   62,   46,
       64,  136,   62,   64,   56,   47,   66,   45,   67,  136,
       73,  291,   46,   67,   55,   67,   69,   66,   47,  108,
      108,  108,   69,   69,   45,   73,   56,   69,   74,   97,
       97,  128,   74,   97,  137,  128,  137,  109,   55,  109,
      109,  109,  271,  110,  125,  110,  110,  110,  125,  109,

      266,  111,  264,  111,   74,  110,  111,  111,  111,  260,
       74,  257,  109,  113,   74,  113,  113,  113,  110,  125,
      256,  135,  162,  162,  255,  113,  135,  254,   74,   87,
      114,   87,  114,  114,  114,   87,  216,  216,  113,  253,
      252,  125,  114,  249,   87,   87,  182,  182,  182,  183,
      183,  183,  184,  184,  184,  114,  182,  244,  242,   87,
      220,  241,  220,   87,   87,  220,  220,  220,   87,  182,
      247,  247,  247,  240,  239,   87,  237,  236,   87,  235,
       87,  233,   87,  231,   87,  248,  248,  248,  228,  227,
       87,  275,  275,  275,  275,  275,  275,  275,  276,  276,

      276,  276,  276,  276,  276,  277,  277,  277,  277,  277,
      277,  277,  278,  278,  278,  278,  278,  278,  278,  279,
      279,  279,  279,  279,  279,  279,  280,  280,  280,  280,
      280,  280,  280,  281,  281,  281,  281,  281,  281,  281,
      282,  282,  282,  282,  282,  282,  282,  283,  226,  283,
      283,  283,  283,  283,  284,  284,  285,  225,  285,  215,
      285,  285,  286,  286,  286,  286,  286,  286,  286,  287,
      214,  213,  287,  287,  287,  288,  211,  288,  210,  288,
      288,  289,  209,  208,  289,  289,  289,  290,  290,  290,
      290,  290,  290,  290,  206,  205,  204,  203,  201,  200,

      199,  198,  197,  194,  193,  192,  191,  189,  188,  187,
      186,  177,  175,  156,  155,  154,  153,  152,  151,  150,
      149,  147,  146,  143,  141,  140,  139,  138,  134,  133,
      132,  131,  130,  127,  126,  124,  123,  105,  103,  101,
      100,   99,   95,   94,   92,   77,   75,   72,   71,   70,
       68,   65,   63,   58,   51,   49,   44,   39,   36,   32,
       31,   29,   27,   23,    6,    5,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,

      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "parathon.l"
#line 2 "parathon.l"
#include <malloc.h>
#include <math.h>
#include <stdio.h>
#include <limits.h>
#include <readline/readline.h>
#include <readline/history.h>
#include "buffer.h"
#include "ast.h"
#include "lexer.h"

#include "parathon.yy.hh"

#define LEXER_ERROR(format) printf("Lexer error, line %d:\n\t" format "\n", line_num); return 0;
#define SYNTAX_ERROR_(error) printf("Syntax error, line %d:\n\t%s\n", line_num, error);
#define SYNTAX_ERROR(format, ...) printf("Syntax error, line %d:\n\t" format "\n", line_num, __VA_ARGS__);
//#define LEX_DEBUG(format, ...) printf("lex, %d: " format "\n", line_num, __VA_ARGS__);
#define LEX_DEBUG(...) ;

#define YY_INPUT(buf, result, size) { result = parathon_input(buf, size, yyextra); } 

// This leaks memory like anything, lucky we imported a global GC 
int parathon_input(char * buf, int size, yy_extra_type* extra)
{
    size_t size_t_size = (size_t) size;
    if (!extra->line_read)
    {
        if (extra->finished) 
            return 0;

        if (isatty(fileno(extra->file)))
        {
            rl_instream = extra->file;
            extra->line_read = readline("> ");
        }
        else
        {
            extra->line_read = NULL;
            extra->length_read = getline(&(extra->line_read), &size_t_size, extra->file);
            if (extra->length_read == -1)
            {
                extra->line_read = NULL;
                extra->length_read = 0;
            }
        }
        if (! extra->line_read)
        {
            extra->finished = 1;
            extra->line_read = (char *)";";
        }
        else if (*extra->line_read)
        {
            add_history (extra->line_read);
        }

        extra->length_read = strlen(extra->line_read);
    }
    int end_offset = extra->length_read - extra->offset_read + 1;
    if (end_offset < size)
    {
        strncpy(buf, extra->line_read + extra->offset_read, end_offset);
        buf[end_offset - 1] = '\n';
        buf[end_offset] = '\0';
        extra->line_read = NULL;
        return end_offset;
    }
    else
    {
        printf("Line too long, maximum is: %d bytes\n", size);
        exit(1);
    }
    
}

#ifndef YYTOKENTYPE
typedef enum LEX_TOKEN {
    TOK_ERROR=0, 
    /* Indents */
    TOK_NEWLINE, TOK_INDENT, TOK_OUTDENT, 
    /* Numbers */
    TOK_INTEGER, TOK_FLOAT,
    /* Brackets */
    TOK_OPEN_SQUARE, TOK_CLOSE_SQUARE,
    TOK_OPEN_CURLY, TOK_CLOSE_CURLY,
    TOK_OPEN_CURVED, TOK_CLOSE_CURVED,
    /* Strings */
    TOK_NAME, TOK_STRING,
// punctuation
    /* Basic syntax */
    TOK_DOT, TOK_COMMA, TOK_COLON, TOK_SEMICOLON, TOK_ASSIGN, TOK_AT, TOK_BACKTICK
    /* Comparisons */
    TOK_EQ, TOK_GT, TOK_GTEQ, TOK_LT, TOK_LTEQ, TOK_NOTEQ,
    /* Arithmetic */
    TOK_PLUS, TOK_MINUS, TOK_MULTIPLY, TOK_DIVIDE, TOK_TRUNC_DIVIDE,
    TOK_POWER, TOK_MODULUS,
    /* Binary */
    TOK_BAND, TOK_BOR, TOK_BNOT, TOK_BXOR,
    /* Shifting */
    TOK_LEFTSHIFT, TOK_RIGHTSHIFT,
// keywords
    /* Conditions */
    TOK_AND, TOK_NOT, TOK_OR, TOK_IN, TOK_IS, 
    /* If statements */
    TOK_IF, TOK_ELIF, TOK_ELSE, 
    /* Block side-effects */
    TOK_PASS, TOK_RETURN, TOK_YIELD, TOK_PRINT, 
    /* Loops */
    TOK_FOR, TOK_WHILE, TOK_BREAK, TOK_CONTINUE, 
    /* Exceptions */
    TOK_TRY, TOK_ASSERT, TOK_RAISE, TOK_EXCEPT, TOK_FINALLY, 
    /* Definitions */
    TOK_CLASS, TOK_DEF, TOK_LAMBDA, 
    /* Names */
    TOK_FROM, TOK_GLOBAL, TOK_IMPORT, TOK_AS, 
    /* etc. */
    TOK_WITH, TOK_DEL, TOK_EXEC 
} LEX_TOKEN;
#endif

// Keep track of current line number for providing reasonable error messages;
unsigned int line_num = 1;
unsigned int bracket_count = 0;

/**
 * This function keeps track of indentation levels and causes the 
 * emission of INDENT and OUTDENT tokens as necessary.
 return 0;
 *
 * The indent_stack is an array of chars, the first of which is always 0
 * corresponding to the left-hand margin. Every time an INDENT is emitted,
 * a new value is pushed onto the stack (higher than the previous). When the
 * indentation decreases, an OUTDENT is emitted for every item that must be
 * popped from the stack in order to leave the last item equal to the new
 * indent. (If the indentation level of an OUTDENT is not in the stack, an
 * error is raised).
 *
 * As with python a tab is eight spaces wide.
 */
 
int handle_indentation(char * yytxt, yy_extra_type* extra)
{
    unsigned int cpos = 0;
    unsigned char indent_level = 0;

    // Find the indentation of this line.
    while (yytxt[cpos + 1] && indent_level < UCHAR_MAX)
    {
        if (yytxt[cpos] == ' ')
        {
            indent_level += 1;
        }
        else if (yytxt[cpos] == '\t')
        {
            indent_level += 8;
        }
        else
        {
            LEXER_ERROR("Unexpected leading whitespace.");
        }
        cpos++;
    }

    if (indent_level == UCHAR_MAX)
    {
        SYNTAX_ERROR_("Maximum indentation level exceded.");
        return IND_ERROR;
    }
    // An "indent"
    else if (indent_level > extra->indent_stack[extra->current_indent]) 
    {
        if (++extra->current_indent == INDENT_STACK_LENGTH)
        {
            SYNTAX_ERROR_("Maximum nested depth exceded.");
            return IND_ERROR;
        }
        else
        {
            extra->indent_stack[extra->current_indent] = indent_level;
            LEX_DEBUG("%s %d", "indent", indent_level);
            return IND_IN;
        }
    } 
    // An "outdent"
    else if (indent_level < extra->indent_stack[extra->current_indent]) 
    {
        if (extra->current_indent <= 0)
        {
            LEXER_ERROR("Unexpected unindent.");
        }
        else if (indent_level > extra->indent_stack[extra->current_indent - 1])
        {
            SYNTAX_ERROR("Unindent to incorrect column: %d", indent_level);
            return IND_ERROR;
        }
        else
        {
            --extra->current_indent;
            LEX_DEBUG("%s %d", "outdent", extra->indent_stack[extra->current_indent]);
            return IND_OUT;
        }
    }
    // Same indentation
    else
    {
        LEX_DEBUG("%s %d", "nodent", extra->indent_stack[extra->current_indent]);
        return IND_SAME;
    }

};

/** String handling, just some wrappers around buffers **/
// Ideally these would be functions, but we need to return and BEGIN
#define begin_string(type) \
    yyextra->cur_str = new_buffer(); \
    BEGIN(type);

#define append_string() \
    if (bputs(yyextra->cur_str, yytext)) {\
        SYNTAX_ERROR_("String too big");\
        BEGIN(ERROR);\
    }

#define append_char(c) \
    if (bputc(yyextra->cur_str, c)) {\
        SYNTAX_ERROR_("String too big");\
        BEGIN(ERROR);\
    }

#define end_string() \
    LEX_DEBUG("%s '%s'", "string", yyextra->cur_str->string);\
    BEGIN(NORMAL); \
    yylval->string = read_and_reset(yyextra->cur_str);\
    old_buffer(yyextra->cur_str);\
    return TOK_STRING;


/** Bracket handling. Needed to avoid whitespace taking effect within brackets **/
#define open_bracket(type) \
    if (bracket_count == UINT_MAX) \
    { \
        LEXER_ERROR("Exceded bracket count"); \
    } \
    else \
    { \
        bracket_count++; \
        LEX_DEBUG("%s%s", "open", yytext); \
        return TOK_OPEN_ ## type; \
    }

#define close_bracket(type) \
    if (!bracket_count || !--bracket_count) \
    { \
        BEGIN(NORMAL); \
    } \
    LEX_DEBUG("%s%s", "close", yytext); \
    return TOK_CLOSE_ ## type;











#line 910 "<stdout>"

#define INITIAL 0
#define NORMAL 1
#define ERROR 2
#define STR1 3
#define STR2 4
#define STR3 5
#define STR6 6
#define RSTR1 7
#define RSTR2 8
#define RSTR3 9
#define RSTR6 10

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (yyscan_t yyscanner );

int yyget_debug (yyscan_t yyscanner );

void yyset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra (yyscan_t yyscanner );

void yyset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *yyget_in (yyscan_t yyscanner );

void yyset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *yyget_out (yyscan_t yyscanner );

void yyset_out  (FILE * out_str ,yyscan_t yyscanner );

int yyget_leng (yyscan_t yyscanner );

char *yyget_text (yyscan_t yyscanner );

int yyget_lineno (yyscan_t yyscanner );

void yyset_lineno (int line_number ,yyscan_t yyscanner );

YYSTYPE * yyget_lval (yyscan_t yyscanner );

void yyset_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (yyscan_t yyscanner );
#else
extern int yywrap (yyscan_t yyscanner );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param ,yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 282 "parathon.l"


#line 1154 "<stdout>"

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		yy_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 275 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 467 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

/*

    This context is entered into at the start of any line when indentation is significant,
    i.e. while not in strings or brackets.

    It should be provable that all possible lines match either of these patterns:

    case 1: The first character on the line is [^ \t#\n], 
        will match rule 1.
    case 2: The first character on the line is #, or the line is empty (equivalent to first character is \n), 
        will match rule 2.
    case 3: The first character on the line is [ \t], 
        can treat the second character on a line as if it were the first as [ \t] is subsumed into [ \t]* both times.
    By induction, either rule 1 or rule 2 will match.
*/
case 1:
YY_RULE_SETUP
#line 300 "parathon.l"
{ // If there is something on the line, then we care about the indentation.

    switch (handle_indentation(yytext, yyextra)) 
    {
        case IND_ERROR:
            fprintf(stderr, "Hello");
            return TOK_ERROR;

        case IND_IN: // Emit INDENT and pass the lookahead to <NORMAL>
            yyless(yyleng - 1);
            BEGIN(NORMAL);
            return TOK_INDENT;

        case IND_OUT: // Emit OUTDENT and loop in <INITIAL> until we get IND_SAME or IND_ERROR
            yyless(0);
            return TOK_OUTDENT;

        case IND_SAME: // pass the lookahead to <NORMAL>
            yyless(yyleng - 1);
            BEGIN(NORMAL);
            break;
    }
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 324 "parathon.l"
{ // If there is nothing of value on the line, the indentation is not of value either.
    LEX_DEBUG("%s", "blank line");
    line_num++;
}
	YY_BREAK


case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 333 "parathon.l"
{ 
    line_num++;
    BEGIN(INITIAL); 
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 338 "parathon.l"
{ // Skip over everything to the end of the line
}
	YY_BREAK

// Newlines are tokens when we are not within brackets or comments
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 345 "parathon.l"
{ // newlines mark the ends of expressions (but only if there are no open brackets)
    if (bracket_count == 0)
    {
        LEX_DEBUG("%s", "newline");
        line_num++;
        BEGIN(INITIAL);
        return TOK_NEWLINE;
    }
    else
    {
        LEX_DEBUG("%s", "ignored line");
        line_num++;
    }
}
	YY_BREAK
case 6:
#line 361 "parathon.l"
case 7:
YY_RULE_SETUP
#line 361 "parathon.l"
{ /* spaces and comments are ignored */ }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 363 "parathon.l"
{
    LEX_DEBUG("%s", "escaped newline");
    line_num++;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 368 "parathon.l"
{ //Floating point numbers

    double number;
    int status;

    status = sscanf(yytext, "%lf", &number);

    if (status == EOF) 
    {
        if (errno == ERANGE) 
        {
            SYNTAX_ERROR("Number out of range: %s", yytext);
        } 
        else
        {
            SYNTAX_ERROR("Error occured while reading number: %s", yytext);
        }
        BEGIN(ERROR);
    }
    else if (status != 1)
    {
        SYNTAX_ERROR("Invalid number: %s", yytext);
        BEGIN(ERROR);
    }
    else
    {
        LEX_DEBUG("%s %f", "float", number)

        yylval->float_val = number;
        return TOK_FLOAT;
    }
}
	YY_BREAK
case 10:
#line 402 "parathon.l"
case 11:
#line 403 "parathon.l"
case 12:
YY_RULE_SETUP
#line 403 "parathon.l"
{

    char *failed = NULL;
    long long number;

    errno = 0;
    number = strtoll(yytext, &failed, 0);

    if (errno == ERANGE) 
    {
        SYNTAX_ERROR("Number out of range: %s", yytext);
        BEGIN(ERROR);
    }
    else if (*failed != '\0') 
    {
        SYNTAX_ERROR("Invalid number: %s\n", yytext);
        BEGIN(ERROR);
    }
    else
    {
        LEX_DEBUG("%s %lld", "integer", number);

        yylval->int_val = number;
        return TOK_INTEGER;
    }
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 430 "parathon.l"
open_bracket(SQUARE);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 431 "parathon.l"
open_bracket(CURLY);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 432 "parathon.l"
open_bracket(CURVED);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 433 "parathon.l"
close_bracket(SQUARE);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 434 "parathon.l"
close_bracket(CURLY);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 435 "parathon.l"
close_bracket(CURVED);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 437 "parathon.l"
begin_string(STR1);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 438 "parathon.l"
begin_string(STR2);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 439 "parathon.l"
begin_string(STR3);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 440 "parathon.l"
begin_string(STR6);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 442 "parathon.l"
begin_string(RSTR1);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 443 "parathon.l"
begin_string(RSTR2);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 444 "parathon.l"
begin_string(RSTR3);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 445 "parathon.l"
begin_string(RSTR6);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 447 "parathon.l"
SYNTAX_ERROR_("Unicode strings are not supported");
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 448 "parathon.l"
SYNTAX_ERROR_("Unicode strings are not supported");
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 449 "parathon.l"
SYNTAX_ERROR_("Unicode strings are not supported");
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 450 "parathon.l"
SYNTAX_ERROR_("Unicode strings are not supported");
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 452 "parathon.l"
return TOK_DOT;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 453 "parathon.l"
return TOK_COMMA;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 454 "parathon.l"
return TOK_SEMICOLON;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 455 "parathon.l"
return TOK_COLON;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 456 "parathon.l"
return TOK_ASSIGN;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 457 "parathon.l"
return TOK_AT;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 458 "parathon.l"
return TOK_BACKTICK;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 460 "parathon.l"
return TOK_PLUS;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 461 "parathon.l"
return TOK_MINUS;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 462 "parathon.l"
return TOK_MULTIPLY;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 463 "parathon.l"
return TOK_POWER;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 464 "parathon.l"
return TOK_DIVIDE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 465 "parathon.l"
return TOK_TRUNC_DIVIDE;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 466 "parathon.l"
return TOK_MODULUS;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 468 "parathon.l"
return TOK_LT;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 469 "parathon.l"
return TOK_GT;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 470 "parathon.l"
return TOK_NOTEQ;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 471 "parathon.l"
return TOK_EQ;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 472 "parathon.l"
return TOK_NOTEQ;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 473 "parathon.l"
return TOK_LTEQ;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 474 "parathon.l"
return TOK_GTEQ;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 476 "parathon.l"
return TOK_BXOR;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 477 "parathon.l"
return TOK_BAND;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 478 "parathon.l"
return TOK_BNOT;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 479 "parathon.l"
return TOK_BOR;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 480 "parathon.l"
return TOK_LEFTSHIFT;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 481 "parathon.l"
return TOK_RIGHTSHIFT;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 483 "parathon.l"
return TOK_AND;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 484 "parathon.l"
return TOK_NOT;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 485 "parathon.l"
return TOK_OR;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 486 "parathon.l"
return TOK_IN;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 487 "parathon.l"
return TOK_IS;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 489 "parathon.l"
return TOK_IF;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 490 "parathon.l"
return TOK_ELIF;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 491 "parathon.l"
return TOK_ELSE;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 493 "parathon.l"
return TOK_PASS;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 494 "parathon.l"
return TOK_RETURN;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 495 "parathon.l"
return TOK_YIELD;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 496 "parathon.l"
return TOK_PRINT;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 498 "parathon.l"
return TOK_FOR;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 499 "parathon.l"
return TOK_WHILE;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 500 "parathon.l"
return TOK_BREAK;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 501 "parathon.l"
return TOK_CONTINUE;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 503 "parathon.l"
return TOK_TRY;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 504 "parathon.l"
return TOK_ASSERT;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 505 "parathon.l"
return TOK_RAISE;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 506 "parathon.l"
return TOK_EXCEPT;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 507 "parathon.l"
return TOK_FINALLY;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 509 "parathon.l"
return TOK_CLASS;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 510 "parathon.l"
return TOK_DEF;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 511 "parathon.l"
return TOK_LAMBDA;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 513 "parathon.l"
return TOK_FROM;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 514 "parathon.l"
return TOK_GLOBAL;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 515 "parathon.l"
return TOK_IMPORT;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 516 "parathon.l"
return TOK_AS;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 518 "parathon.l"
return TOK_WITH;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 519 "parathon.l"
return TOK_DEL;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 520 "parathon.l"
return TOK_EXEC;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 522 "parathon.l"
{ // A variable name
    LEX_DEBUG("%s '%s'", "name", yytext);
    yylval->name = strdup(yytext);
    return TOK_NAME;
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 528 "parathon.l"
{
    SYNTAX_ERROR("Unexpected '%s'", yytext);
}
	YY_BREAK

// 'single quoted string'
case 91:
YY_RULE_SETUP
#line 534 "parathon.l"
end_string();
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 535 "parathon.l"
append_string();
	YY_BREAK

// "double quoted string"
case 93:
YY_RULE_SETUP
#line 539 "parathon.l"
end_string();
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 540 "parathon.l"
append_string();
	YY_BREAK

// '''triple quoted string'''
case 95:
YY_RULE_SETUP
#line 544 "parathon.l"
end_string();
	YY_BREAK
case 96:
#line 546 "parathon.l"
case 97:
YY_RULE_SETUP
#line 546 "parathon.l"
append_string();
	YY_BREAK

// """6-quoted string"""
case 98:
YY_RULE_SETUP
#line 550 "parathon.l"
end_string();
	YY_BREAK
case 99:
#line 552 "parathon.l"
case 100:
YY_RULE_SETUP
#line 552 "parathon.l"
append_string();
	YY_BREAK

// single-line strings
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 556 "parathon.l"
{
    BEGIN(INITIAL);
    SYNTAX_ERROR_("End of line within single-quoted string.")
    line_num++;
}
	YY_BREAK

// multi-line strings
case 102:
/* rule 102 can match eol */
YY_RULE_SETUP
#line 564 "parathon.l"
{
    append_string();
    LEX_DEBUG("%s", "string newline");
    line_num++;
}
	YY_BREAK

// All strings - backslash escapes from http://www.python.org/doc/2.5.4/ref/strings.html
case 103:
YY_RULE_SETUP
#line 573 "parathon.l"
{
    unsigned long n = strtol(yytext + 1, NULL, 16);
    append_char((unsigned char) n);
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 578 "parathon.l"
{
    BEGIN(ERROR);
    SYNTAX_ERROR_("Invalid \\x escape");
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 583 "parathon.l"
{
    // NOTE: as with CPython this silently takes n % 256
    unsigned long n = strtol(yytext + 1, NULL, 8);
    append_char((unsigned char) n);
}
	YY_BREAK
case 106:
/* rule 106 can match eol */
YY_RULE_SETUP
#line 589 "parathon.l"
{
    LEX_DEBUG("%s", "escaped newline");
    line_num++;
}
	YY_BREAK
case 107:
#line 595 "parathon.l"
case 108:
#line 596 "parathon.l"
case 109:
YY_RULE_SETUP
#line 596 "parathon.l"
append_char(yytext[1]);
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 598 "parathon.l"
append_char('\a');
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 599 "parathon.l"
append_char('\b');
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 600 "parathon.l"
append_char('\f');
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 601 "parathon.l"
append_char('\n');
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 602 "parathon.l"
append_char('\r');
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 603 "parathon.l"
append_char('\t');
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 604 "parathon.l"
append_char('\v');
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 605 "parathon.l"
append_string();
	YY_BREAK

// Raw strings - backslashes are literals (but need special handling for \" etc.)

case 118:
/* rule 118 can match eol */
#line 612 "parathon.l"
case 119:
/* rule 119 can match eol */
YY_RULE_SETUP
#line 612 "parathon.l"
append_string();
	YY_BREAK

case 120:
YY_RULE_SETUP
#line 616 "parathon.l"
ECHO;
	YY_BREAK
#line 1989 "<stdout>"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(NORMAL):
case YY_STATE_EOF(ERROR):
case YY_STATE_EOF(STR1):
case YY_STATE_EOF(STR2):
case YY_STATE_EOF(STR3):
case YY_STATE_EOF(STR6):
case YY_STATE_EOF(RSTR1):
case YY_STATE_EOF(RSTR2):
case YY_STATE_EOF(RSTR3):
case YY_STATE_EOF(RSTR6):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 275 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 275 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 274);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	yy_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf ,yyscanner );

	yyfree((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "yyset_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "yyset_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void yyset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int yylex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */

int yylex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    yyset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 616 "parathon.l"



#ifndef YYTOKENTYPE
int main (int argc, char* argv)
{
   int c;
    while (c = yylex());

    printf("Bye\n\n");
    return 0;
}
#endif

